name: Build theme

on: [commit]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: Install dependencies for the theme, build it
      shell: bash
      run: |
        npm install
        npm install gulp-livereload@^3.8.1
        npm run build
